;       _________________________________________________________________________________________
;
;       Esta libreria contiene las constantes requeridas para el algoritmo de interpolacion
;       _________________________________________________________________________________________

; %assign FILE_SIZE               15
; %assign MATRIX_SRC_SIZE         4
; %assign MATRIX_OUT_SIZE         16
; %assign ROW_SIZE_SRC            2
; %assign ROW_SIZE_OUT            4
; %assign LAST_INDEX_OUT          3

%assign FILE_SIZE               35
%assign MATRIX_SRC_SIZE         9
%assign MATRIX_OUT_SIZE         49
%assign ROW_SIZE_SRC            3
%assign ROW_SIZE_OUT            7
%assign LAST_INDEX_OUT          6

; %assign FILE_SIZE               63
; %assign MATRIX_SRC_SIZE         16
; %assign MATRIX_OUT_SIZE         100
; %assign ROW_SIZE_SRC            4
; %assign ROW_SIZE_OUT            10
; %assign LAST_INDEX_OUT          9

; %assign FILE_SIZE               37635 
; %assign MATRIX_SRC_SIZE         9409
; %assign MATRIX_OUT_SIZE         83521
; %assign ROW_SIZE_SRC            97
; %assign ROW_SIZE_OUT            289
; %assign LAST_INDEX_OUT          288

; %assign FILE_SIZE               3600 
; %assign MATRIX_SRC_SIZE         900
; %assign MATRIX_OUT_SIZE         7744
; %assign ROW_SIZE_SRC            30
; %assign ROW_SIZE_OUT            88
; %assign LAST_INDEX_OUT          87


%assign MASK            0xff
%assign ASCII_SPACE     -16
%assign ASCII_END       -48