;       _________________________________________________________________________________________
;
;       Esta libreria contiene las constantes requeridas para el algoritmo de interpolacion
;       _________________________________________________________________________________________

; Imagen 2x2
; %assign FILE_SIZE               15
; %assign MATRIX_SRC_SIZE         4
; %assign MATRIX_OUT_SIZE         16
; %assign ROW_SIZE_SRC            2
; %assign ROW_SIZE_OUT            4
; %assign LAST_INDEX_OUT          3

;   Imagen 3x3
; %assign FILE_SIZE               35
; %assign MATRIX_SRC_SIZE         9
; %assign MATRIX_OUT_SIZE         49
; %assign ROW_SIZE_SRC            3
; %assign ROW_SIZE_OUT            7
; %assign LAST_INDEX_OUT          6

; ; Imagen 4x4
; %assign FILE_SIZE               63
; %assign MATRIX_SRC_SIZE         16
; %assign MATRIX_OUT_SIZE         100
; %assign ROW_SIZE_SRC            4
; %assign ROW_SIZE_OUT            10
; %assign LAST_INDEX_OUT          9

; ; ; Imagen 5x5
; %assign FILE_SIZE               100
; %assign MATRIX_SRC_SIZE         25
; %assign MATRIX_OUT_SIZE         169
; %assign ROW_SIZE_SRC            5
; %assign ROW_SIZE_OUT            13
; %assign LAST_INDEX_OUT          12

; ; Imagen 6x6
; %assign FILE_SIZE               143
; %assign MATRIX_SRC_SIZE         36
; %assign MATRIX_OUT_SIZE         256
; %assign ROW_SIZE_SRC            6
; %assign ROW_SIZE_OUT            16
; %assign LAST_INDEX_OUT          15



; ; Imagen 10x10
; %assign FILE_SIZE               399
; %assign MATRIX_SRC_SIZE         100
; %assign MATRIX_OUT_SIZE         784
; %assign ROW_SIZE_SRC            10
; %assign ROW_SIZE_OUT            28
; %assign LAST_INDEX_OUT          27


; ; Imagen 30x30
; %assign FILE_SIZE               3600 
; %assign MATRIX_SRC_SIZE         900
; %assign MATRIX_OUT_SIZE         7744
; %assign ROW_SIZE_SRC            30
; %assign ROW_SIZE_OUT            88
; %assign LAST_INDEX_OUT          87


; Imagen 97x97
%assign FILE_SIZE               37635 
%assign MATRIX_SRC_SIZE         9409
%assign MATRIX_OUT_SIZE         83521
%assign ROW_SIZE_SRC            97
%assign ROW_SIZE_OUT            289
%assign LAST_INDEX_OUT          288


%assign MASK            0xff
%assign MASK2            0xfff
%assign MASK3            0x1ffff
%assign ASCII_SPACE     -16
%assign ASCII_END       -48